version = 0.1

[default.deploy.parameters]
stack_name = "jyelle-sts-dev"
s3_prefix = "jyelle-sts-dev"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Owner=\"jeremy.yelle@caylent.com\" Environment=\"dev\" StackName=\"sts\""
resolve_s3 = true
image_repositories = []

[default.build.parameters]
cached = true
parallel = true
[default.global.parameters]
region = "us-east-2"
